import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Full Stack Web Development',
    rating: 5,
    ratingCount: 267,
    price: 49999,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'Full Stack Software Engineering',
    rating: 5,
    ratingCount: 341,
    price: 89999,
    category: 'Beginner',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Python For Beginners',
    rating: 5,
    ratingCount: 129,
    price: 19999,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'Complete Guide For MS Excel',
    rating: 5,
    ratingCount: 257,
    price: 19999,
    category: 'Beginner',
  },
  {
    id: 5,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Deep Dive Into MYSql',
    rating: 5,
    ratingCount: 257,
    price: 19999,
    category: 'Beginner',
  },
  {
    id: 6,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'Data Modeling',
    rating: 5,
    ratingCount: 257,
    price: 19999,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'Statistics',
    rating: 5,
    ratingCount: 257,
    price: 19999,
    category: 'Beginner',
  },
]
